export const CLASSES = [
    {
        id: 120,
        type: 'group',
        className: 'Antenatal class',
        tags: ['pregnancy', 'parenting'],
        date: "2019-08-03T10:30Z",
        time: '10h30',
        duration: "10h (3 sessions)",
        city: "Madrid",
        district: "Chueca",
        address: "Paseo de las Castellana 45, Madrid",
        url: 'https://www.belandmums.com/antenatal-course/',
        image: 'antenatal_bm.png',
        companyName: 'Bel & Mums',
        companyLogo: 'bm_logo.png',
        label: 'New',
        price: 330,
        language: 'english',
        featured: true,
        description: "Our Prenatal Classes are interactive and enjoyable where you will always feel respected and supported."
    },
    {
        id: 1,
        type: 'group',
        className: 'First Aid (baby and child)',
        tags: ['health', 'baby'],
        date: "2019-09-05T10:30Z",
        time: '10h30',
        duration: '3h',
        city: "Madrid",
        district: "Chueca",
        address: "Paseo de las Castellana 45, Madrid",
        url: 'https://www.belandmums.com/first-aid-course/',
        image: 'baby.png',
        companyName: 'Bel & Mums',
        companyLogo: 'bm_logo.png',
        label: 'New',
        language: 'english',
        price: 45,
        featured: false,
        description: "Children are unpredictable and fearless and, although emergency situations rarely occur, their solutions are often easy and effective. " 
        + "The course is addressed to parents and any person under the care of a minor."
        + "Is a theoretical-practical course and all the attendants practice with the baby and child mannequins under direct supervision."
        + "The places are limited to 8 to ensure an excellent quality."
        + "The instructor is a Certified Pediatric Nurse and Midwife with a wide experience on this field."
        + "If you need a pediatric first aid certificate please let us know when you book the course."  
    },
    {
        id: 2,
        type: 'group',
        className: 'Pregnancy Activo',
        tags: ['pregnancy', 'health'],
        address: 'CDM GO fit Vallehermoso',
        city: "Madrid",
        district: "Chueca",
        date: "2019-08-22T17:00Z",
        time: '12h45',
        duration: '1h',
        url: 'http://www.go-fit.es/Horarios/Index/1564610400/embarazo%20activo',
        image: 'active_pregnancy_gf.png',
        companyName: 'Go Fit',
        companyLogo: 'gf_logo.png',
        label: 'New',
        language: 'spanish',
        price: 100,
        featured: false,
        description: "Our Prenatal Classes are interactive and enjoyable where you will always feel respected and supported."
    },
    {
        id: 4,
        type: 'group',
        className: 'Breastfeeding Class',
        tags: ['breastfeeding'],
        city: "Madrid",
        district: "Chueca",
        address: "Paseo de las Castellana 45, Madrid",
        date: "2019-08-01T16:00Z",
        time: '16h00',
        duration: '2h',
        url: 'https://www.belandmums.com/breastfeeding/',
        image: 'breastfeeding_bm.png',
        companyName: 'Bel & Mums',
        companyLogo: 'bm_logo.png',
        label: 'New',
        price: 60,
        language: 'english',
        spacesLeft: 0,
        featured: false,
        description: "Our Prenatal Classes are interactive and enjoyable where you will always feel respected and supported."
    },
    {
        id: 100,
        type: 'group',
        className: 'Antenatal class',
        tags: ['pregnancy'],
        date: "2019-09-07T10:30Z",
        time: '10h30',
        duration: "10h (3 sessions)",
        city: "Madrid",
        district: "Chueca",
        address: "Paseo de las Castellana 45, Madrid",
        url: 'https://www.belandmums.com/antenatal-course/',
        image: 'antenatal_bm.png',
        companyName: 'Bel & Mums',
        companyLogo: 'bm_logo.png',
        label: 'New',
        price: 330,
        language: 'english',
        featured: true,
        description: "Our Prenatal Classes are interactive and enjoyable where you will always feel respected and supported."
    },
    {
        id: 3,
        type: 'group',
        className: 'Taller de Mindfulness y embarazo',
        tags: ['pregnancy', 'health'],
        city: "Madrid",
        district: "Chueca",
        address: 'CDM GO fit Vallehermoso',
        date: "2019-08-22T17:00Z",
        time: '12h45',
        duration: "1h",
        url: 'http://www.go-fit.es/Horarios/Index/1564610400/embarazo%20activo',
        image: 'rinconmindfulness.png',
        companyName: 'El Rincon De Mindfulness',
        companyLogo: 'rm_logo.jpg',
        language: 'spanish',
        label: 'New',
        price: 50,
        featured: false,
        description: "Taller de cuatro sesiones de dos horas y media cada una, que se imparte en nuestro Centro en Madrid, diseñado especialmente para embarazadas, con o sin sus parejas, por Pilar Pardinas. Cada vez aparecen más estudios sobre la eficacia de intervenciones basadas en Mindfulness dirigidas expresamente a las embarazadas. Se ha observado que la reducción del estrés percibido y de la ansiedad, además de la regulación emocional, influyen positivamente, no solo en la forma de vivir el proceso del embarazo, sino en la disminución de complicaciones durante éste y en un mejor manejo del dolor durante el parto." 
    },
    {
        id: 5,
        type: 'group',
        className: 'Breastfeeding Class',
        tags: ['breastfeeding'],
        city: "Madrid",
        district: "Chueca",
        address: "Paseo de las Castellana 45, Madrid",
        date: "2019-09-05T17:00Z",
        time: '17h00',
        duration: '2h',
        url: 'https://www.belandmums.com/breastfeeding/',
        image: 'breastfeeding.png',
        companyName: 'Bel & Mums',
        companyLogo: 'bm_logo.png',
        label: 'New',
        price: 60,
        language: 'english',
        spacesLeft: 5,
        featured: false,
        description: "Our Prenatal Classes are interactive and enjoyable where you will always feel respected and supported."
    },
    {
        id: 0,
        type: 'group',
        className: 'Antenatal class',
        tags: ['pregnancy', 'health'],
        date: "2019-09-07T16:00Z",
        time: '16h00',
        duration: "10h (3 sessions)",
        city: "Madrid",
        district: "Chueca",
        address: "Paseo de las Castellana 45, Madrid",
        url: 'https://www.belandmums.com/preparacion-parto/',
        image: 'antenatal_bm.png',
        companyName: 'Bel & Mums',
        companyLogo: 'bm_logo.png',
        label: 'New',
        price: 330,
        language: 'spanish',
        featured: true,
        description: "Our Prenatal Classes are interactive and enjoyable where you will always feel respected and supported."
    },
    {
        id: 6,
        type: 'group',
        className: 'Breastfeeding Class',
        tags: ['breastfeeding', 'nutrition'],
        city: "Madrid",
        district: "Chueca",
        address: "Paseo de las Castellana 45, Madrid",
        date: "2019-10-03T17:00Z",
        time: '17h00',
        duration: '2h',
        url: 'https://www.belandmums.com/breastfeeding/',
        image: 'breastfeeding.png',
        companyName: 'Bel & Mums',
        companyLogo: 'bm_logo.png',
        label: 'New',
        price: 60,
        language: 'english',
        spacesLeft: 5,
        featured: false,
        description: "Our Prenatal Classes are interactive and enjoyable where you will always feel respected and supported."
    },
];