export const CLASSES = [
    {
        id: 0,
        className: 'Antenatal class',
        category: 'Pregnancy',
        date: "2019-08-02T17:00Z",
        time: '17:00',
        duration: 60,
        url: 'https://www.belandmums.com/antenatal-course/',
        image: 'images/antenatal.png',
        companyName: 'Bel & Mums',
        label: 'New',
        price: 300,
        featured: true,
    },
    {
        id: 1,
        className: 'First Aid',
        category: 'Aid',
        date: "2019-08-01T17:00Z",
        time: '17:00',
        duration: 60,
        url: 'https://www.belandmums.com/antenatal-course/',
        image: 'images/baby.png',
        companyName: 'Bel & Mums',
        label: 'New',
        price: 300,
        featured: false
    },
    {
        id: 2,
        className: 'Pregnancy Activo',
        category: 'Pregnancy',
        address: 'CDM GO fit Vallehermoso',
        date: "2019-08-22T17:00Z",
        time: '12:45',
        duration: 60,
        url: 'http://www.go-fit.es/Horarios/Index/1564610400/embarazo%20activo',
        image: 'images/gofitlogo.jpg',
        companyName: 'Go Fit',
        label: 'New',
        price: 100,
        featured: false
    },
];