export const CLASSES = [
    {
        id: 120,
        className: 'Antenatal class',
        category: 'Pregnancy',
        date: "2019-08-03T10:30Z",
        time: '10:30',
        duration: "10h (3 sessions)",
        address: "Paseo de las Castellana 45, Madrid",
        url: 'https://www.belandmums.com/antenatal-course/',
        image: 'images/antenatal.png',
        companyName: 'Bel & Mums',
        label: 'New',
        price: 330,
        language: 'English',
        featured: true,
    },
    {
        id: 100,
        className: 'Antenatal class',
        category: 'Pregnancy',
        date: "2019-09-07T10:30Z",
        time: '10:30',
        duration: "10h (3 sessions)",
        address: "Paseo de las Castellana 45, Madrid",
        url: 'https://www.belandmums.com/antenatal-course/',
        image: 'images/antenatal2.png',
        companyName: 'Bel & Mums',
        label: 'New',
        price: 330,
        language: 'English',
        featured: true,
    },
    {
        id: 0,
        className: 'Antenatal class',
        category: 'Pregnancy',
        date: "2019-09-07T16:00Z",
        time: '16:00',
        duration: "10h (3 sessions)",
        address: "Paseo de las Castellana 45, Madrid",
        url: 'https://www.belandmums.com/preparacion-parto/',
        image: 'images/antenatal2.png',
        companyName: 'Bel & Mums',
        label: 'New',
        price: 330,
        language: 'Spanish',
        featured: true,
    },
    {
        id: 1,
        className: 'First Aid',
        category: 'Aid',
        date: "2019-08-01T17:00Z",
        time: '17:00',
        duration: 60,
        url: 'https://www.belandmums.com/antenatal-course/',
        image: 'images/baby.png',
        companyName: 'Bel & Mums',
        label: 'New',
        price: 300,
        featured: false
    },
    {
        id: 2,
        className: 'Pregnancy Activo',
        category: 'Pregnancy',
        address: 'CDM GO fit Vallehermoso',
        date: "2019-08-22T17:00Z",
        time: '12:45',
        duration: 60,
        url: 'http://www.go-fit.es/Horarios/Index/1564610400/embarazo%20activo',
        image: 'images/gofitlogo.jpg',
        companyName: 'Go Fit',
        label: 'New',
        price: 100,
        featured: false
    },
    {
        id: 3,
        className: 'Taller de Mindfulness y embarazo',
        category: 'Pregnancy',
        address: 'CDM GO fit Vallehermoso',
        date: "2019-08-22T17:00Z",
        time: '12:45',
        duration: 60,
        url: 'http://www.go-fit.es/Horarios/Index/1564610400/embarazo%20activo',
        image: 'images/rinconmindfulness.png',
        companyName: 'El Rincon De Mindfulness',
        label: 'New',
        price: 100,
        featured: false
    },
    {
        id: 4,
        className: 'Breastfeeding Class',
        category: 'Breastfeeding',
        address: "Paseo de las Castellana 45, Madrid",
        date: "2019-08-01T16:00Z",
        time: '16:00',
        duration: 120,
        url: 'https://www.belandmums.com/breastfeeding/',
        image: 'images/breastfeeding.png',
        companyName: 'Bel & Mums',
        label: 'New',
        price: 60,
        language: 'English',
        spacesLeft: 0,
        featured: false
    },
    {
        id: 5,
        className: 'Breastfeeding Class',
        category: 'Breastfeeding',
        address: "Paseo de las Castellana 45, Madrid",
        date: "2019-09-05T17:00Z",
        time: '17:00',
        duration: 120,
        url: 'https://www.belandmums.com/breastfeeding/',
        image: 'images/breastfeeding.png',
        companyName: 'Bel & Mums',
        label: 'New',
        price: 60,
        language: 'English',
        spacesLeft: 5,
        featured: false
    },
    {
        id: 6,
        className: 'Breastfeeding Class',
        category: 'Breastfeeding',
        address: "Paseo de las Castellana 45, Madrid",
        date: "2019-10-03T17:00Z",
        time: '17:00',
        duration: 120,
        url: 'https://www.belandmums.com/breastfeeding/',
        image: 'images/breastfeeding.png',
        companyName: 'Bel & Mums',
        label: 'New',
        price: 60,
        language: 'English',
        spacesLeft: 5,
        featured: false
    },
];