const past = [{
    id: 4,
    type: 'group',
    className: 'Breastfeeding Class',
    tags: ['breastfeeding'],
    city: "Madrid",
    district: "Almagro",
    address: "Paseo de las Castellana 45, Madrid",
    date: "2019-08-01T16:00Z",
    time: '16h00',
    duration: '2h',
    url: 'https://www.belandmums.com/breastfeeding/',
    image: 'breastfeeding_bm.jpg',
    companyName: 'Bel & Mums',
    companyLogo: 'bm_logo.png',
    label: 'New',
    price: 60,
    language: 'english',
    spacesLeft: 0,
    featured: false,
    description: [
        "Our Prenatal Classes are interactive and enjoyable where you will always feel respected and supported.",
    ],
},
{
    id: 2,
    type: 'group',
    className: 'Pregnancy Activo',
    tags: ['pregnancy', 'health'],
    address: 'CDM GO fit Vallehermoso',
    city: "Madrid",
    district: "Chueca",
    date: "2019-08-22T12:45Z",
    time: '12h45',
    duration: '1h',
    url: 'http://www.go-fit.es/Horarios/Index/1564610400/embarazo%20activo',
    image: 'active_pregnancy_gf.jpg',
    companyName: 'Go Fit',
    companyLogo: 'gf_logo.png',
    label: 'New',
    language: 'spanish',
    price: 100,
    featured: false,
    description: [
        "Our Prenatal Classes are interactive and enjoyable where you will always feel respected and supported.",
    ],
},
{
    id: 21,
    type: 'group',
    className: 'Natación para Bebés',
    tags: ['baby', 'health'],
    address: 'CDM GO fit Vallehermoso',
    city: "Madrid",
    district: "Vallehermoso",
    date: "2019-08-22T12:45Z",
    time: '12h45',
    duration: '1h',
    url: 'http://www.go-fit.es/Cursos/Detalle/natacion_para_bebes',
    image: 'swimming.jpg',
    companyName: 'Go Fit',
    companyLogo: 'gf_logo.png',
    label: 'New',
    language: 'spanish',
    price: 40,
    featured: false,
    description: [
        "Disfruta con tu bebé desde su nacimiento con las clases de natación que GO fit ha preparado para que os divirtáis juntos.",
    ],
},
{
    id: 3,
    type: 'group',
    className: 'Mindfulness y embarazo',
    tags: ['pregnancy', 'health'],
    city: "Madrid",
    district: "Chueca",
    address: 'CDM GO fit Vallehermoso',
    date: "2019-08-22T17:00Z",
    time: '12h45',
    duration: "1h",
    url: 'http://www.go-fit.es/Horarios/Index/1564610400/embarazo%20activo',
    image: 'rinconmindfulness.jpg',
    companyName: 'El Rincon De Mindfulness',
    companyLogo: 'rm_logo.png',
    language: 'spanish',
    label: 'New',
    price: 50,
    featured: false,
    description: [
        "Taller de cuatro sesiones de dos horas y media cada una, que se imparte en nuestro Centro en Madrid, diseñado especialmente para embarazadas, con o sin sus parejas, por Pilar Pardinas.",
        "Cada vez aparecen más estudios sobre la eficacia de intervenciones basadas en Mindfulness dirigidas expresamente a las embarazadas.",
        "Se ha observado que la reducción del estrés percibido y de la ansiedad, además de la regulación emocional, influyen positivamente, no solo en la forma de vivir el proceso del embarazo, sino en la disminución de complicaciones durante éste y en un mejor manejo del dolor durante el parto.",
    ],
},
{
    id: 5,
    type: 'group',
    className: 'Clase de Lactancia Materna',
    tags: ['breastfeeding'],
    city: "Madrid",
    district: "Almagro",
    address: "Paseo de las Castellana 45, Madrid",
    date: "2019-09-04T17:00Z",
    time: '17h00',
    duration: '2h',
    url: 'https://www.belandmums.com/breastfeeding/',
    image: 'breastfeeding_bm.jpg',
    companyName: 'Bel & Mums',
    companyLogo: 'bm_logo.png',
    label: 'New',
    price: 60,
    language: 'spanish',
    spacesLeft: 5,
    featured: false,
    description: [
        "La lactancia materna es el mejor regalo que puedes darle a tu bebé y es muy reconfortante pero requiere mucho esfuerzo y dedicación.",
        "Por eso es muy recomendable asistir a un buen curso de lactancia durante el embarazo y así estar bien preparada desde su primera toma.",
    ],
},
{
    id: 0,
    type: 'group',
    className: 'Preparación al Parto',
    tags: ['pregnancy', 'health'],
    date: "2019-09-07T17:00Z",
    time: '16h00',
    duration: "10h",
    city: "Madrid",
    district: "Almagro",
    address: "Paseo de las Castellana 45, Madrid",
    url: 'https://www.belandmums.com/preparacion-parto/',
    image: 'antenatal_2.jpg',
    companyName: 'Bel & Mums',
    companyLogo: 'bm_logo.png',
    label: 'New',
    price: 330,
    language: 'spanish',
    featured: true,
    description: [
        "Se trata de un curso interactivo y ameno en el que te sentirás a gusto y acompañada.",
        "Ofrece una formación muy completa para que, llegado el momento de tu parto, recuperación y primeras semanas con tu bebé, puedas contar con la información y técnicas más importantes sobre vuestro cuidado y así disfrutar de esta etapa sintiéndote segura.",
    ],
},
{
    id: 100,
    type: 'group',
    className: 'Antenatal class',
    tags: ['pregnancy'],
    date: "2019-09-07T10:30Z",
    time: '10h30',
    duration: "10h",
    city: "Madrid",
    district: "Almagro",
    address: "Paseo de las Castellana 45, Madrid",
    url: 'https://www.belandmums.com/antenatal-course/',
    image: 'antenatal_2.jpg',
    companyName: 'Bel & Mums',
    companyLogo: 'bm_logo.png',
    label: 'New',
    price: 330,
    language: 'english',
    featured: true,
    description: [
        "Our Prenatal Classes are interactive and enjoyable where you will always feel respected and supported.", 
        "It is also a very complete course that, once the time of your labour, recovery and first weeks with your baby come, you will be able to employ the best cares feeling secure.",
        "You will learn the most updated techniques and useful information so you can understand and work with you body on a safe and effective way. ",
        "The course is very practical and informative so you and your partner will learn all you need to know and only in one weekend! ",
        "It is not only a course but a nice experience that includes: 2 sessions in couple (8h) + 1 women only session (2h) + \"the expecting parents group dinner\" + continuos midwifery support : ",
        "2 Sessions in Couple: you will learn and practice all you need to know to get ready for your childbirth, recovery and baby cares. ",
        "1 Women Only Session: To solve all those questions that you may choose to discuss among women only. It is a maternity Q&A in a very friendly environment where you can also make friends that attended other courses. ",
        "The Expecting Parents Dinner: We know how valuable is to have a supporting network of English-speakers in Madrid during this special time in your life. We are taking you out to strengthen the group's friendship even more! ",
        "Continuous Support: From the time you book this Antenatal Course you will have our contact number and will have our support. ",
    ],
},
{
    id: 62,
    type: 'group',
    className: 'Taller intensivo de Disciplina Positiva',
    tags: ['parenting'],
    city: "Madrid",
    district: "Pedrezuela",
    address: "Paseo de la Ermita, 43. PEDREZUELA",
    date: "2019-09-07T10:00Z",
    time: '10h00',
    duration: '7h',
    url: 'https://infanciaenpositivo.com/tienda/taller-de-disciplina-positiva-de-pareja-en-madrid-ref-tdp',
    image: 'infanciaenpositivo.jpg',
    companyName: 'Infancia en Positivo',
    companyLogo: 'infanciaenpositivo.png',
    label: 'New',
    price: 90,
    language: 'spanish',
    spacesLeft: 5,
    featured: false,
    description: [
        "En este Taller te muestro cómo la Disciplina Positiva desde sus orígenes con la psicología Adleriana, hasta hoy ha ayudado a cientos de madres y padres a resolver los comportamientos inadecuados de sus hijos así como seguir la misma línea de crianza con tu pareja.",
        "Empleando herramientas respetuosas que ayudan a lograr un ambiente más armónico en tu hogar.",
        "Aprenderás a conocerte mejor y comprobarás cómo funciona el cerebro de tus hijos para comprender sus pensamientos y creencias, cuáles son sus necesidades y cómo podemos responder ante ellas de la manera más asertiva."
    ],
},
{
    id: 65,
    type: 'group',
    className: 'TALLER DE PORTEO ERGONÓMICO',
    tags: ['parenting', 'music'],
    city: "Madrid",
    district: "Prosperidad",
    address: "Calle Pradillo 10",
    date: "2019-09-07T11:00Z",
    time: '11h00',
    duration: '1h',
    url: 'https://elultimokoala.com/actividades/6757-taller-de-portabebes-ergonomicos.html',
    image: 'elultimokoala.jpg',
    companyName: 'El Ultimo Koala',
    companyLogo: 'ultimokoala.png',
    label: 'New',
    price: 0,
    language: 'spanish',
    spacesLeft: 5,
    featured: false,
    description: [
        "¿Estáis embarazos y queréis aprender a portear a vuestro bebé? ¿Vuestro bebé ha nacido y queréis portearle? Este es vuestro taller. Aprenderemos las bases para un porteo seguro y conoceremos los diferentes tipos de portabebés ergonómicos para que podáis probar y elegir cuál se adapta mejor a vuestros gustos y necesidades antes de comprarlo?",
        "Contenido del Taller:",
        "Primera parte teórica:",
        "- Hablaremos sobre la necesidad de los bebés de ser llevados, el origen del porteo y su evolución.",
        "- Explicaremos los beneficios que tiene llevar cerca a nuestros bebés para ellos y para nosotros, las pautas para portear con seguridad,  posición adecuada y las características a tener en cuenta para poder distinguir los portabebés ergonómicos de los que no lo son.",
        "Segunda parte práctica:",
        "- Aprenderemos cómo se utilizan los portabebés ergonómicos más frecuentes; fular elástico, fular tejido, mochilas 0 a 6 meses, mochilas a partir de 6 meses y reductores, bandoleras, mei tais...para qué edades y usos son más adecuados.",
        "- Podréis probarlos con vuestro bebé o con nuestros muñecos de prueba para conocer cuál es el más adecuado para vosotros.",
    ],
},
];