export const PROVIDERS = [
    {
        id: 10,
        name: 'Bel & Mum',
        address: "Paseo de las Castellana 45, Madrid",
        url: 'https://www.belandmums.com/antenatal-course/',
        logo: 'belandmums',
        featured: false,
        city: "Madrid",
        classes: [],
        online: false,
    },
    {
        id: 12,
        name: 'Go Fit',
        address: 'CDM GO fit Vallehermoso',
        url: 'http://www.go-fit.es/Centros/Centro/cdm_vallehermoso',
        logo: 'gofit',
        featured: true,
        city: "Madrid",
        classes: [],
        online: false,
    },
    {
        id: 13,
        name: 'El Rincon de Mindfulness',
        address: '',
        url: 'https://www.rinconmind.org',
        logo: 'elrinconmindfulness',
        featured: true,
        city: "Madrid",
        classes: [],
        online: false,
    },
    {
        id: 14,
        name: 'Mami Fit',
        address: '',
        url: 'https://www.mamifit.es',
        logo: 'mamifit',
        featured: true,
        city: "Madrid",
        classes: [],
        online: false,
    },
    {
        id: 15,
        name: 'Alopeke',
        address: '',
        url: 'http://mundoalopeke.com/',
        logo: 'alopeke',
        featured: false,
        city: "Madrid",
        classes: [],
        online: false,
    },
    {
        id: 16,
        name: 'BabySalus',
        address: '',
        url: 'https://www.babysalus.es/',
        logo: 'babysalus',
        featured: false,
        city: "Madrid",
        classes: [],
        online: false,
    },
    {
        id: 17,
        name: 'Padres Ayudando A Padres',
        address: '',
        url: 'https://tienda.padresayudandoapadres.es/',
        logo: 'padresayudando',
        featured: false,
        city: "Madrid",
        classes: [],
        online: false,
    },
    {
        id: 18,
        name: 'Infancia en Positivo',
        address: '',
        url: 'https://infanciaenpositivo.com/',
        logo: 'infanciaenpositivo',
        featured: false,
        city: "Madrid",
        classes: [],
        online: false,
    },
    {
        id: 19,
        name: 'Vidaes',
        address: '',
        url: 'https://www.vidaes.es',
        logo: 'vidaes',
        featured: false,
        city: "Madrid",
        classes: [],
        online: false,
    },
    {
        id: 20,
        name: 'Creciendomisol',
        address: '',
        url: 'https://www.creciendomisol.com',
        logo: 'creciendomisol',
        featured: false,
        city: "Madrid",
        classes: [],
        online: false,
    },
    {
        id: 21,
        name: 'Fisiomedit',
        address: '',
        url: 'https://fisiomedit.com/',
        logo: 'fisiomedit',
        featured: false,
        city: "Madrid",
        classes: [],
        online: false,
    },
    {
        id: 37,
        name: 'Bienvenido Bebé',
        address: '',
        url: 'https://bienvenidobebe.es',
        logo: 'bienvenidobebe',
        featured: false,
        classes: [],
        online: true,
    },
    {
        id: 24,
        name: 'DailyOM',
        address: '',
        url: 'https://dailyom.com/',
        logo: 'dailyom',
        featured: false,
        classes: [],
        online: true,
    },
    {
        id: 25,
        name: 'Udemy',
        address: '',
        url: 'https://udemy.com/',
        logo: 'udemy',
        featured: false,
        classes: [],
        online: true,
    },
    {
        id: 26,
        name: 'Escuela Bitacoras',
        address: '',
        url: 'https://escuela.bitacoras.com/cursos/',
        logo: 'escuelabitacoras',
        featured: false,
        classes: [],
        online: true,
    },
    {
        id: 27,
        name: 'Monica Serrano',
        address: '',
        url: 'https://www.psicologiaycrianza.com/',
        logo: 'monikaserrano',
        featured: false,
        classes: [],
        online: true,
    },
    {
        id: 28,
        name: 'Edurespeta',
        address: '',
        url: 'https://www.edurespeta.com/',
        logo: 'edurespeta',
        featured: false,
        classes: [],
        online: true,
    },
    {
        id: 30,
        name: 'Escuela Baby Tribu',
        address: '',
        url: 'https://escuelababytribu.com',
        logo: 'escuelababytribu',
        featured: false,
        classes: [],
        online: true,
    },
    {
        id: 31,
        name: 'Gestionando Hijos',
        address: '',
        url: 'https://gestionandohijos.com',
        logo: 'gestionandohijos',
        featured: false,
        classes: [],
        online: true,
    },
    {
        id: 32,
        name: 'Educar en Calma',
        address: '',
        url: 'https://educarencalma.com',
        logo: 'educarencalma',
        featured: false,
        city: "Madrid",
        classes: [],
        online: false,
    },
    {
        id: 33,
        name: 'Materna Yoga',
        address: '',
        url: 'https://maternayoga.es',
        logo: 'maternayoga',
        featured: false,
        city: "Madrid",
        classes: [],
        online: false,
    },
    {
        id: 34,
        name: 'Pequeños Maestros',
        address: '',
        url: 'https://pequeñosmaestros.com',
        logo: 'pequenosmaestros',
        featured: false,
        city: "Madrid",
        classes: [],
        online: false,
    },
    {
        id: 35,
        name: 'Entre Mamas',
        address: '',
        url: 'https://www.entremamas.org/',
        logo: 'entremamas',
        featured: false,
        city: "Madrid",
        classes: [],
        online: false,
    },
    {
        id: 36,
        name: 'Espacio Kenko',
        address: '',
        url: 'https://espaciokenko.com',
        logo: 'espaciokenko',
        featured: false,
        city: "Madrid",
        classes: [],
        online: false,
    },
    {
        id: 92,
        name: 'Coursera',
        address: '',
        url: 'https://coursera.com/',
        logo: 'coursera',
        featured: false,
        classes: [],
        online: true,
    },
    {
        id: 23,
        name: 'EdX',
        address: '',
        url: 'https://edx.com/',
        logo: 'edx',
        featured: false,
        classes: [],
        online: true,
    },
    
];