export const RESOURCES = [
    {
        id: 1000,
        type: 'online',
        className: 'Child Nutrition and Cooking',
        tags: ['parenting', 'nutrition'],
        duration: "5 weeks (9h)",
        image: 'childnutritionandcooking.jpg',
        url: 'https://www.coursera.org/learn/childnutrition',   
        companyName: 'Coursera',
        companyLogo: 'coursera_logo.jpg',
        label: '',
        price: 'Free Online Course (Audit)',
        language: 'english',
        featured: true,
        description: "Eating patterns that begin in childhood affect health and well-being across the lifespan. The culture of eating has changed significantly in recent decades, especially in parts of the world where processed foods dominate our dietary intake. This course examines contemporary child nutrition and the impact of the individual decisions made by each family. The health risks associated with obesity in childhood are also discussed. Participants will learn what constitutes a healthy diet for children and adults and how to prepare simple, delicious foods aimed at inspiring a lifelong celebration of easy home-cooked meals. This course will help prepare participants to be the leading health providers, teachers and parents of the present and future.The text and other material in this course may include the opinion of the specific instructor and are not statements of advice, endorsement, opinion, or information of Stanford University."    
    },
    {
        id: 1001,
        type: 'online',
        className: 'Nutrition and Lifestyle in Pregnancy',
        tags: ['nutrition', 'parenting'],
        duration: "5 weeks (8h)",
        image: 'nutrition_pregnancy_coursera.jpg',
        url: 'https://www.coursera.org/learn/nutrition-pregnancy',  
        companyName: 'Coursera', 
        companyLogo: 'coursera_logo.jpg',
        label: '',
        price: 'Free Online Course (Audit)',
        language: 'english',
        featured: false,
        description: "Nutrition and Lifestyle in Pregnancy offers an overview of the latest research findings and international recommendations on a variety of nutrition-related aspects and outcomes of pregnancy.  Ensuring a healthy nutritional status and lifestyle prior to and during pregnancy is one of the best ways to help support the healthy growth and development of the unborn child. We will look at how a healthy diet and lifestyle should ideally be achieved prior to conception and provide recommendations for pre-conception counselling of women."
    },
    {
        id: 1002,
        type: 'online',
        className: 'Everyday Parenting: The ABCs of Child Rearing',
        tags: ['parenting'],
        duration: "4 weeks (14h)",
        image: 'everydayparenting.jpg',
        url: 'https://www.coursera.org/learn/everyday-parenting',  
        companyName: 'Coursera', 
        companyLogo: 'coursera_logo.jpg',
        label: '',
        price: 'Free Online Course (Audit)',
        language: 'english',
        featured: false,
        description: [
            "Everyday Parenting gives you access to a toolkit of behavior-change techniques that",
            "will make your typical day in the home easier as you develop the behaviors you would",
            "like to see in your child. The lessons provide step-by-step instructions and demonstrations",
            "to improve your course of action with both children and adolescents.  Among many techniques, ",
            "you will learn how even simple modifications to tone of voice and phrasing can lead to more",
            "compliance.  The course will also shed light on many parenting misconceptions and ineffective",
            "strategies that are routinely used."
        ]
    },
    {
        id: 1004,
        type: 'online',
        className: 'Conscious Parenting',
        tags: ['parenting'],
        duration: "5 weeks (9h)",
        image: 'dailyom.jpg',
        url: 'https://www.dailyom.com/cgi-bin/courses/courseoverview.cgi?cid=845&aff=92&cur=eur&ad=2019062473&img=40&utm_medium=social&utm_source=ig&utm_campaign=Conscious+Parenting+%5Bcid%3D845%5D-2019-06-24&utm_content=motherhood-Instagram_Feed&g=f',   
        companyName: 'DailyOM',
        companyLogo: 'dailyom.jpg',
        label: '',
        price: 15,
        language: 'english',
        featured: true,
        description: "Every parent desires a close and connected relationship with their children. Despite their greatest desire and intentions, this relationship is often rife with anxiety, conflict and stress. Instead of this relationship being joyful and empowered, it ends up being embittered and complex. Despite their parent's best intentions, children often grow up feeling misunderstood and invalidated. This disconnect is heartbreaking for parents who seem to want nothing more than the closest bond with their offspring."
    },
    {
        id: 1005,
        type: 'online',
        className: 'Lengua de Signos para Bebes Oyentes',
        tags: ['parenting'],
        duration: "30min",
        image: 'lenguadesignes.jpg',
        url: 'https://www.udemy.com/course/lengua-de-signos-para-bebes-oyentes/',   
        companyName: 'Udemy',
        companyLogo: 'udemy.png',
        label: '',
        price: 24.99,
        language: 'spanish',
        featured: true,
        description: "Every parent desires a close and connected relationship with their children. Despite their greatest desire and intentions, this relationship is often rife with anxiety, conflict and stress. Instead of this relationship being joyful and empowered, it ends up being embittered and complex. Despite their parent's best intentions, children often grow up feeling misunderstood and invalidated. This disconnect is heartbreaking for parents who seem to want nothing more than the closest bond with their offspring."
    },
    {
        id: 1006,
        type: 'online',
        className: 'The Science of Parenting',
        tags: ['parenting'],
        duration: "5 weeks",
        image: 'scienceparenting.jpg',
        url: 'https://www.edx.org/course/the-science-of-parenting-2',   
        companyName: 'EdX',
        companyLogo: 'edx.png',
        label: '',
        price: 0,
        language: 'english',
        featured: true,
        description: [
            "Everyone has an opinion on parenting – where babies should sleep, what they should eat, and whether parents should spank, scold, or praise. What’s more, the media often offers support for whichever opinions appear most popular at any given time. This leaves those of us who like to base our decisions on firm, provable facts feeling dizzy.",
            "\"The Science of Parenting\" addresses this confusion by moving beyond the chatter and opinion surrounding parenting, and by looking directly at the science. Parenting itself is far from a science. Nevertheless, scientists have conducted thousands of studies that can help parents – or future parents – make sensible, informed decisions.",
        ],
    },
    {
        id: 1003,
        type: 'meetup',
        className: 'The Bumps Tea',
        tags: [],
        district: "Chamberí",
        address: 'Paseo de la Castellana 45',
        date: "2019-09-04T11:00Z",
        duration: "1h30",
        image: 'bumps_tea.jpg',
        url: 'https://www.belandmums.com/informative-sessions/',  
        companyName: 'Bel & Mums',
        companyLogo: 'bm_logo.png',
        label: '',
        price: 6,
        language: 'english',
        featured: false,
        description: "At Bel & Mums we know how valuable it is to have a supporting network during pregnancy and postnatally. We also know how tricky this can be in a city like Madrid specially if you have just moved in. We want to help you creating your community and get to know other women in your same situation.",    },
];